version: '2'
volumes:
  deps:

services:
  client:
    image: node:14
    working_dir: /usr/src/app
    command: npm run client
    volumes:
      - .:/usr/src/app
      - deps:/usr/src/app/node_modules
    expose:
      - 3001
    ports:
      - 3001:3001
  server:
    image: node:14
    working_dir: /usr/src/app
    command: npm run server
    volumes:
      - .:/usr/src/app
      - deps:/usr/src/app/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000
